import {useState,useEffect,useRef} from 'react';
import {Mark,Icon} from './Mark.jsx';
import {api} from '../client.js';
import {dateLabel} from '../shared.js';

const groups=[['Работа',[['today','Сегодня','projects'],['applications','Заявки','applications'],['projects','Свадьбы','projects'],['tasks','Задачи','projects'],['calendar','Календарь','projects']]],['Управление',[['agency','Финансы агентства','agencyFinance'],['settings','Настройки','settings']]]];
const tabs=[['overview','Обзор','project'],['tasks','План','tasks'],['approvals','Согласования','approvals'],['catalog','Подрядчики','vendors'],['estimate','Финансы','budget'],['guests','Гости','guest'],['seating','Рассадка','seating'],['timing-pair','День свадьбы','timing'],['timing-team','Тайминг','timing'],['files','Документы','files'],['more','Ещё','more']];
const spaceTabs={organizer:['overview','tasks','approvals','catalog','estimate','guests','seating','timing-pair','files','more'],couple:['overview','tasks','approvals','catalog','estimate','guests','seating','timing-pair','files','more'],contractor:['tasks','timing-team','files','more']};
const projectLinks={couple:[['project:overview','Наша свадьба','projects'],['project:tasks','План','tasks'],['project:approvals','Согласования','approvals'],['project:catalog','Подрядчики','catalog'],['project:estimate','Финансы','estimate'],['project:guests','Гости','guests'],['project:seating','Рассадка','seating'],['project:timing-pair','День свадьбы','timing'],['project:files','Документы','files']],contractor:[['project:tasks','Задачи','tasks'],['project:timing-team','Тайминг команды','timing'],['project:files','Документы','files'],['project:tables','Рабочие таблицы','templates']]};
const landing=space=>space==='contractor'?'project:tasks':'project:overview';

export function AppShell({state,view,setView,selectedProject,onProject,onLogout,children,workspaceMode='organizer',onWorkspace,availableProjects=[]}){
 const[menu,setMenu]=useState(false),[unread,setUnread]=useState(0),[search,setSearch]=useState('');
 const menuButton=useRef(null),drawer=useRef(null),restoreMenuFocus=useRef(false);
 const u=state.user,p=state.project||selectedProject,isProject=view.startsWith('project:');
 const global=new Set((state.grants||[]).filter(g=>g.project_id==null).flatMap(g=>g.permissions||[]));
 const staff=u.protected||global.has('projects');
 const canSwitch=!!onWorkspace&&(u.protected||(state.grants||[]).some(g=>g.project_id===null&&g.role_key==='admin'));
 const contractor=!staff&&(state.grants||[]).some(g=>g.role_key==='contractor')&&!(state.grants||[]).some(g=>g.role_key==='couple');
 const space=canSwitch?workspaceMode:staff?'organizer':contractor?'contractor':'couple';
 const roleSpace=space!=='organizer',projects=availableProjects.length?availableProjects:state.projects||[];
 const allowed=section=>u.protected||(state.grants||[]).some(g=>(g.project_id===null||g.project_id===p?.id)&&g.permissions.includes('read')&&(!g.restrictions?.sections?.length||g.restrictions.sections.includes(section)));
 const closeMenu=(restoreFocus=false)=>{if(restoreFocus)restoreMenuFocus.current=true;setMenu(false)};
 const nav=next=>{if(setView(next)!==false&&menu)closeMenu(true)};
 const chooseProject=project=>{onProject(project,landing(space));if(menu)closeMenu(true)};
 useEffect(()=>{drawer.current?.querySelector('nav')?.setAttribute('id','primary-navigation')},[]);
 useEffect(()=>{if(!menu)return;const host=drawer.current,main=document.querySelector('.v2-main-column'),bottom=document.querySelector('.v2-bottom-nav'),focusable=()=>[...host.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex="0"]')].filter(node=>node.getClientRects().length);const first=focusable()[0];main&&(main.inert=true);bottom&&(bottom.inert=true);first?.focus();const key=event=>{if(event.key==='Escape'){event.preventDefault();closeMenu(true);return}if(event.key!=='Tab')return;const all=focusable(),start=all[0],end=all.at(-1);if(!all.length){event.preventDefault();return}if(event.shiftKey&&document.activeElement===start){event.preventDefault();end.focus()}else if(!event.shiftKey&&document.activeElement===end){event.preventDefault();start.focus()}};host.addEventListener('keydown',key);return()=>{host.removeEventListener('keydown',key);main&&(main.inert=false);bottom&&(bottom.inert=false)}},[menu]);
 useEffect(()=>{if(menu||!restoreMenuFocus.current)return;restoreMenuFocus.current=false;menuButton.current?.focus()},[menu]);
 useEffect(()=>{let live=true;api('/api/v2/notifications?limit=1').then(r=>{if(live)setUnread(r.unread)}).catch(()=>{if(live)setUnread(0)});return()=>{live=false}},[state.time]);
 const visibleTabs=tabs.filter(([id,,section])=>spaceTabs[space].includes(id)&&(['project','more'].includes(section)||section==='guest'?(section!=='guest'||(state.entities||[]).some(t=>t.kind==='table'&&t.data.key==='guests')):section==='timing'?(state.entities||[]).some(t=>t.kind==='table'&&t.data.key==='timing'):allowed(section)));
 const searchResults=search.trim()?projects.filter(project=>(project.data.name+' '+project.data.date+' '+(project.data.location||'')).toLocaleLowerCase('ru').includes(search.trim().toLocaleLowerCase('ru'))).slice(0,8):[];
 const chooseSearch=project=>{setSearch('');chooseProject(project)};
 const key=view.split(':')[1],goSearch=e=>{e.preventDefault();if(searchResults[0])chooseSearch(searchResults[0])};
 const roleLinks=(projectLinks[space]||[]).filter(([id])=>id==='project:overview'||id==='project:tables'||id==='project:tasks'||allowed(({catalog:'vendors',estimate:'budget',guests:'guest',seating:'seating','timing-pair':'timing','timing-team':'timing',files:'files',approvals:'approvals'})[id.split(':')[1]]||id.split(':')[1]));
 return <div className={`app-shell v2-shell ${staff?'is-staff':'is-couple'} space-${space}`}>
  <aside ref={drawer} className={`sidebar ${menu?'v2-menu-open':''}`}>
   <div className="sidebar-top"><button className="brand brand-button" onClick={()=>nav(roleSpace?p?landing(space):staff?'projects':'applications':'today')}><Mark compact/><span>tie</span></button><small className="v2-agency-label">{state.agency.name}</small></div>
   {roleSpace&&projects.length>0&&<label className="v2-space-project"><span>Свадьба</span><select aria-label="Выбрать свадьбу" value={p?.id||''} onChange={event=>{const target=projects.find(project=>project.id===event.target.value);if(target)chooseProject(target)}}><option value="">Выберите свадьбу</option>{projects.map(project=><option key={project.id} value={project.id}>{project.data.name}</option>)}</select></label>}
   <nav aria-label="Основная навигация">{space==='organizer'&&staff?groups.map(([name,items])=><div className="v2-nav-group" key={name}><small>{name}</small>{items.filter(([id,,permission])=>u.protected||global.has(permission)||id==='settings'&&(state.canManageUsers||global.has('catalog')||global.has('templates')||global.has('agencyFinance'))).map(([id,label])=>{const active=view===id||isProject&&id==='projects';return <button key={id} className={active?'active':''} aria-current={active?'page':undefined} onClick={()=>nav(id)} title={label}><Icon name={id}/><span>{label}</span></button>})}</div>):<div className="v2-nav-group"><small>{space==='contractor'?'Пространство подрядчиков':'Пространство молодожёнов'}</small>{staff&&<button onClick={()=>nav('projects')} className={view==='projects'?'active':''} aria-current={view==='projects'?'page':undefined} title="Все свадьбы"><Icon name="projects"/><span>Все свадьбы</span></button>}{p&&roleLinks.map(([id,label,icon])=>{const active=view===id||view.startsWith(id+':');return <button key={id} onClick={()=>nav(id)} className={active?'active':''} aria-current={active?'page':undefined} title={label}><Icon name={icon}/><span>{label}</span></button>})}{canSwitch&&<button onClick={()=>nav('settings')} className={view==='settings'?'active':''} aria-current={view==='settings'?'page':undefined} title="Настройки"><Icon name="settings"/><span>Настройки</span></button>}{!staff&&<button onClick={()=>nav('notifications')} aria-current={view==='notifications'?'page':undefined}><Icon name="notifications"/><span>Уведомления</span></button>}</div>}<button className="mobile-nav-logout" onClick={onLogout}><Icon name="logout"/><span>Выйти</span></button></nav>
   <div className="sidebar-bottom"><button onClick={onLogout}><Icon name="logout"/><span>Выйти</span></button></div>
  </aside>
  <div className="v2-main-column"><header className="v2-topbar"><button ref={menuButton} className="v2-menu-toggle icon-button" aria-label={menu?'Закрыть навигацию':'Открыть навигацию'} aria-expanded={menu} aria-controls="primary-navigation" onClick={()=>setMenu(!menu)}><Icon name="menu"/></button><form className="v2-global-search" onSubmit={goSearch}><Icon name="search"/><input aria-label="Поиск по доступным проектам" placeholder="Найти свадьбу" value={search} onChange={e=>setSearch(e.target.value)}/>{search.trim()&&<div className="v2-search-results">{searchResults.length?searchResults.map(project=><button key={project.id} type="button" onClick={()=>chooseSearch(project)}>{project.data.name}<small>{dateLabel(project.data.date)}</small></button>):<p role="status">Свадьбы не найдены</p>}</div>}</form><div className="v2-topbar-actions"><button className="icon-button v2-bell" aria-label={`Уведомления: ${unread} непрочитанных`} onClick={()=>nav('notifications')}><Icon name="notifications"/>{unread>0&&<b>{unread>99?'99+':unread}</b>}</button><button className="v2-profile-button" onClick={()=>nav('profile')}><span className="avatar">{u.name.slice(0,1)}</span><span>{u.name}</span></button></div></header>
   <main className="workspace">{roleSpace&&view==='projects'&&<div className="v2-space-intro"><span>{space==='contractor'?'Подрядчики':'Молодожёны'}</span><p>Выберите свадьбу, чтобы открыть рабочее пространство.</p></div>}{isProject&&p&&<>{staff&&<button className="v2-project-back" onClick={()=>nav('projects')}>← Все свадьбы</button>}<header className="v2-project-header"><div><h1>{p.data.name}</h1><p>{dateLabel(p.data.date)}{p.data.location&&` · ${p.data.location}`} <span className="v2-project-status">{({planning:'Подготовка',confirmed:'Подтверждена',completed:'Завершена',archived:'Архив'})[p.data.status]}</span></p></div>{space!=='contractor'&&<button className="button quiet" onClick={()=>nav('project:settings')}>Настройки свадьбы</button>}</header><nav className="v2-project-tabs" aria-label="Разделы свадьбы">{visibleTabs.map(([id,label])=>{const active=key===id||id==='estimate'&&key==='payouts'||id==='timing-pair'&&key==='timing-team'&&space!=='contractor';return <button key={id} className={active?'active':''} aria-current={active?'page':undefined} onClick={()=>nav('project:'+id)}>{label}</button>})}</nav>{['estimate','payouts'].includes(key)&&<nav className="v2-subtabs"><button className={key==='estimate'?'active':''} aria-current={key==='estimate'?'page':undefined} onClick={()=>nav('project:estimate')}>Смета</button><button className={key==='payouts'?'active':''} aria-current={key==='payouts'?'page':undefined} onClick={()=>nav('project:payouts')}>Предстоящие выплаты</button></nav>}{key?.startsWith('timing')&&<nav className="v2-subtabs">{space!=='contractor'&&<button className={key==='timing-pair'?'active':''} aria-current={key==='timing-pair'?'page':undefined} onClick={()=>nav('project:timing-pair')}>Тайминг пары</button>}<button className={key==='timing-team'?'active':''} aria-current={key==='timing-team'?'page':undefined} onClick={()=>nav('project:timing-team')}>Тайминг команды</button></nav>}</>}{children}</main></div>
  {isProject&&<nav className="v2-bottom-nav" aria-label="Быстрая навигация">{(space==='contractor'?[['tasks','Задачи'],['timing-team','Тайминг'],['files','Файлы'],['more','Ещё']]:[['overview','Обзор'],['tasks','План'],['approvals','Согласования'],['more','Ещё']]).filter(([id])=>visibleTabs.some(([tab])=>tab===id)).map(([id,label])=>{const active=key===id;return <button key={id} className={active?'active':''} aria-current={active?'page':undefined} onClick={()=>nav('project:'+id)}><Icon name={id}/><span>{label}</span></button>})}</nav>}
 </div>;
}
