import {readFileSync} from 'node:fs';
import {mkdtempSync,mkdirSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createHttpServer} from '../server/http.mjs';
import {bootstrap,execute} from '../server/service.mjs';
import {entities,uid} from '../server/db.mjs';
import {createPublicAsset} from '../server/v2/publishing/index.mjs';

const temp=mkdtempSync(join(tmpdir(),'tie-visual-'));mkdirSync(resolve('test-results'),{recursive:true});
const server=createHttpServer({dbPath:join(temp,'test.sqlite'),distDir:resolve('dist')});await new Promise(r=>server.listen(Number(process.env.PORT||4188),'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`,db=server.db,{user}=bootstrap(db,{slug:'tie',agencyName:'tie · визуальная проверка',name:'Мария Соколова',email:'visual@example.test',password:'visual-test-password'}),cmd=(op,body={})=>execute(db,user,{id:uid(),op,...body});
const empty=cmd('project.create',{data:{name:'Новая свадьба',date:'2027-06-12',location:'Москва'}}),filled=cmd('project.create',{data:{name:'Алина и Даниил',date:'2026-09-19',location:'Усадьба «Липы»',limit:245000000}});
for(const [title,offset] of [['Выбрать оформление церемонии',-9],['Утвердить меню банкета',-13],['Собрать ответы гостей',-7],['Проверить рассадку',-5],['Уточнить время приезда декоратора',-8],['Утвердить тайминг пары',-3],['Оплатить остаток за декор',-5],['Передать план рассадки ресторану',-2],['Проверить трансфер гостей',-4],['Собрать контакты подрядчиков',-6],['Заказать букет',-5],['Проверить готовность площадки',-3]])cmd('task.create',{projectId:filled.id,data:{title,dueMode:'relative',offsetDays:offset,assigneeUserId:user.id}});
for(const title of ['Оформление церемонии','Меню свадебного ужина'])cmd('approval.saveDraft',{projectId:filled.id,data:{title,category:'other',approverUserIds:[user.id],policy:'any',options:[{id:uid(),title:'Садовая история',description:'Живые цветы, текстиль и монтаж',price:8500000},{id:uid(),title:'Тёплый вечер',description:'Сезонные цветы и тёплая палитра',price:7200000},{id:uid(),title:'Белая церемония',description:'Светлая флористика и лёгкая арка',price:9600000}]}});
const day=new Intl.DateTimeFormat('sv-SE').format(new Date());
for(const [title,time] of [['Знакомство с парой','10:00'],['Обсуждение площадки','14:00']])cmd('meeting.save',{projectId:filled.id,data:{title,startDate:day,startTime:time,endDate:day,endTime:time.slice(0,2)+':45',timeZone:'Europe/Moscow',assignedUserIds:[user.id],participantUserIds:[],location:'Онлайн'}});
let guests=entities(db,user.agency_id,filled.id,'table').find(t=>t.data.key==='guests');
guests=cmd('entity.edit',{projectId:filled.id,entityId:guests.id,version:guests.version,data:{...guests.data,columns:[...guests.data.columns,{id:'transport',name:'Трансфер',type:'text'},{id:'hotel',name:'Проживание',type:'text'},{id:'note',name:'Комментарий',type:'text'},{id:'seat_table',name:'Стол рассадки',type:'relation',targetKind:'seatingTable'},{id:'seat_index',name:'Место',type:'number'}]}});
guests=cmd('guestMapping.save',{projectId:filled.id,guestTableId:guests.id,schemaVersion:guests.version,confirm:true,data:{semanticMap:{guestName:'name',rsvpStatus:'status',diet:'meal',transfer:'transport',accommodation:'hotel',contact:'contact',comment:'note',seatingTable:'seat_table',seatIndex:'seat_index'}}});
const plan=cmd('seatingPlan.save',{projectId:filled.id,data:{name:'План зала',widthM:12,heightM:8,guestTableId:guests.id,zones:[{label:'Танцпол',xM:4,yM:3,widthM:4,heightM:2}]}});
const tables=[];for(let i=0;i<4;i++)tables.push(cmd('seatingTable.create',{projectId:filled.id,planId:plan.id,planVersion:plan.version,data:{label:`Стол ${i+1}`,shape:'round',xM:1+(i%2)*8,yM:1+Math.floor(i/2)*4,widthM:1.6,heightM:1.6,capacity:8}}));
for(const [index,name] of ['Екатерина Волкова','Иван Платонов','Мария Лаврова','Сергей Мартынов','Анна Беляева','Павел Савельев','Виктория Котова','Алексей Нестеров','Нина Орлова','Артём Соловьёв','Ольга Рыбакова','Дмитрий Чернов','Лидия Морозова','Вадим Соколов','Елена Зорина','Михаил Куликов','Полина Акимова','Кирилл Романов','Софья Ершова','Роман Власов','Наталья Брагина','Глеб Ильин','Вероника Данилова','Максим Аксенов','Дарья Громова','Фёдор Селезнёв','Ирина Фомина','Леонид Крылов','Ксения Жукова','Тимур Осипов','Алина Мельникова','Егор Тарасов'].entries()){const initial=cmd('entity.create',{projectId:filled.id,kind:'row',parentId:guests.id,schemaVersion:guests.version,data:{name,status:'Не отправлено'}});const row=cmd('guest.rsvp.set',{projectId:filled.id,guestTableId:guests.id,schemaVersion:guests.version,guestRowId:initial.id,rowVersion:initial.version,data:{values:{rsvp:'confirmed'}}});if(index<30)cmd('seating.assign',{projectId:filled.id,guestTableId:guests.id,schemaVersion:guests.version,guestRowId:row.id,rowVersion:row.version,tableId:tables[Math.floor(index/8)].id,tableVersion:tables[Math.floor(index/8)].version,seatIndex:(index%8)+1});}

const timing=entities(db,user.agency_id,filled.id,'table').find(t=>t.data.key==='timing');
for(const [time,end,title,place,audience] of [['10:00','11:00','Заезд команды и монтаж','Усадьба «Липы»','Команда'],['13:30','14:15','Сборы пары','Оранжерея','Пара'],['15:00','15:30','Сбор гостей','Welcome-зона','Общее'],['15:30','16:00','Церемония','Сад у арки','Общее'],['17:00','19:00','Ужин и тосты','Основной зал','Общее'],['20:30','23:00','Танцы и вечерняя программа','Основной зал','Общее']])cmd('entity.create',{projectId:filled.id,kind:'row',parentId:timing.id,schemaVersion:timing.version,data:{time,end,title,place,audience,people:'Пара, гости, команда',responsible:'Мария',done:false}});
for(const [title,agreed,planned,dueDate] of [['Площадка и банкет',98000000,98000000,'2026-09-15'],['Декор церемонии и зала',28000000,28000000,'2026-09-14'],['Фотосъёмка',12000000,12000000,'2026-09-19'],['Ведение вечера',9500000,9500000,'2026-09-19'],['Свадебный торт',2800000,2800000,'2026-09-17']])cmd('entity.create',{projectId:filled.id,kind:'obligation',data:{title,priceKind:'amount',agreed,planned,dueDate,fee:false}});
for(const [name,services,price] of [['Анна Миронова','Фотограф · живые эмоции и естественный свет',12000000],['Студия «Ветка»','Декор и флористика',28000000],['Михаил Белый','Ведущий вечера',9500000],['Clover catering','Кейтеринг и сезонное меню',32000000],['Квартет «Сентябрь»','Живая музыка',6500000],['Елена Лесная','Стилист',3500000]])cmd('entity.create',{kind:'vendor',data:{name,services,price,contact:'demo@example.test'}});

let packagePage=cmd('publicContent.saveDraft',{data:{kind:'package',draft:{title:'Организация свадьбы',slug:'wedding-planning',order:1,summary:'Помогаем собрать день от первой встречи до последнего гостя.',audience:'Для пар, которым нужна спокойная и последовательная подготовка.',included:['Концепция и команда','План подготовки','Координация дня'],excluded:['Услуги подрядчиков'],outcome:'Понятный план и собранная команда.',process:'Сначала знакомимся, затем собираем решения в единый маршрут.',priceType:'on_request',priceLabel:'Формат и состав работы обсудим на встрече.'}}});
packagePage=cmd('publicContent.publish',{entityId:packagePage.id,version:packagePage.version,data:{kind:'package'}});
let story=cmd('publicContent.saveDraft',{data:{kind:'case',draft:{title:'Сентябрь в усадьбе',slug:'september-estate',order:1,summary:'Камерный праздник в саду с длинным ужином и близкими людьми.',city:'Москва',venue:'Усадьба «Липы»',season:'Осень',year:'2026',guestCount:42,challenge:'Собрать семейный праздник с разным темпом дня.',solutions:'Сделали тихую церемонию в саду, ужин за одним столом и пространство для вечерних разговоров.',result:'День, где у каждого гостя нашлось своё место.',vendors:['Фотограф'],vendorsApproved:true,photoCredits:'Тестовая визуальная фикстура',serviceIds:[packagePage.id]}}});
const storyAsset=await createPublicAsset(db,user,{ownerId:story.id,content:readFileSync(resolve('docs/v2/prototype/assets/couple.jpg'))});
story=cmd('publicContent.saveDraft',{entityId:story.id,version:story.version,data:{kind:'case',draft:{...story.data.draft,gallery:[{assetId:storyAsset.id,alt:'Пара в саду',caption:'Визуальная фикстура',order:0}]}}});
story=cmd('publicContent.publish',{entityId:story.id,version:story.version,data:{kind:'case'}});
let faq=cmd('publicContent.saveDraft',{data:{kind:'faq',draft:{order:1,question:'Когда стоит начинать подготовку?',answer:'Начните с разговора о вашей дате, составе гостей и том, каким вы хотите помнить этот день.',category:'Подготовка'}}});
faq=cmd('publicContent.publish',{entityId:faq.id,version:faq.version,data:{kind:'faq'}});
let home=cmd('publicSite.saveMainDraft',{data:{draft:{heroTitle:'Ваша история. Внимание к каждой детали.',heroText:'Собираем свадьбы с ясным планом, вниманием к людям и временем для самого важного.',approach:'Не торопим решения: сначала слушаем вас, затем помогаем собрать день в естественном ритме.',steps:['Знакомство и разговор о вашем дне','Концепция, смета и команда','Подготовка и координация события'],benefits:['Единое пространство для пары и команды','Актуальные договорённости и спокойный процесс'],contactText:'Оставьте заявку — начнём с короткого знакомства.'}}});
home=cmd('publicSite.publishMain',{version:home.version});

let weddingSite=cmd('microsite.saveDraft',{projectId:filled.id,data:{rsvpDeadline:'2099-09-12',draft:{template:'photo',coupleNames:'Алина и Даниил',title:'Приглашение на свадьбу',intro:'Будем рады провести этот день рядом с вами.',dateLabel:'19 сентября 2026',venue:'Усадьба «Липы»',dressCode:'Светлые и природные оттенки',dressPalette:'Пыльная роза, олива и молочный',directions:'Въезд на территорию со стороны главных ворот. Координатор встретит гостей у сада.',accommodation:'Если вам понадобится помощь с размещением, сообщите об этом в ответе на приглашение.',transport:'Трансфер от метро отправляется в 14:15. Укажите необходимость трансфера в RSVP.',schedule:[{time:'15:00',title:'Сбор гостей',note:'Встречаемся в саду у оранжереи.'},{time:'15:30',title:'Церемония',note:'Просим занять места за десять минут до начала.'},{time:'17:00',title:'Ужин',note:'Длинный стол в главном зале.'}],contacts:[{label:'Координатор',kind:'text',value:'Мария, в день события'}],mealEnabled:true,transportEnabled:true}}});
const weddingAsset=await createPublicAsset(db,user,{projectId:filled.id,ownerId:weddingSite.id,content:readFileSync(resolve('docs/v2/prototype/assets/wedding.jpg'))});
weddingSite=cmd('microsite.saveDraft',{projectId:filled.id,version:weddingSite.version,data:{rsvpDeadline:'2099-09-12',draft:{...weddingSite.data.draft,gallery:[{assetId:weddingAsset.id,alt:'Свадебная церемония',caption:'Визуальная фикстура приглашения',order:0}]}}});
weddingSite=cmd('microsite.publish',{projectId:filled.id,version:weddingSite.version});
const guestRow=cmd('entity.create',{projectId:filled.id,kind:'row',parentId:guests.id,schemaVersion:guests.version,data:{name:'Нина Орлова',status:'Приглашён'}});
const guestInvite=cmd('guestInvite.create',{projectId:filled.id,guestTableId:guests.id,schemaVersion:guests.version,guestRowIds:[guestRow.id],expiresAt:new Date(Date.now()+7*86400000).toISOString()});
const urls={agencyHome:`${origin}/`,stories:`${origin}/stories`,story:`${origin}/stories/${story.data.slug}`,services:`${origin}/services`,faq:`${origin}/faq`,wedding:`${origin}/w/${weddingSite.data.shareId}`,guestInviteBase:`${origin}/w/${weddingSite.data.shareId}`};
writeFileSync(resolve('test-results/design-preview.private.json'),JSON.stringify({guestInviteUrl:`${urls.guestInviteBase}#invite=${guestInvite.token}`},null,2),{mode:0o600});
writeFileSync(resolve('test-results/design-preview.json'),JSON.stringify({origin,projectId:filled.id,emptyProjectId:empty.id,email:'visual@example.test',password:'visual-test-password',dbPath:join(temp,'test.sqlite'),urls,publications:{homeId:home.id,caseId:story.id,packageId:packagePage.id,faqId:faq.id,weddingSiteId:weddingSite.id,guestInviteId:guestInvite.inviteId}},null,2),{mode:0o600});
console.log(JSON.stringify({origin,projectId:filled.id,emptyProjectId:empty.id,access:'test-results/design-preview.json'}));
