import {createCipheriv,createDecipheriv,createHash,randomBytes} from 'node:crypto';
import {assert,change,entity,entities,Fault,insert,now,transaction,uid} from '../../db.mjs';
import {can,requireAccess} from '../../auth.mjs';
import {currentUser,projectAccess,addDays} from '../common.mjs';
import {taskData} from '../workflow/index.mjs';

const GOOGLE_AUTH='https://accounts.google.com/o/oauth2/v2/auth';
const GOOGLE_TOKEN='https://oauth2.googleapis.com/token';
const GOOGLE_API='https://www.googleapis.com/calendar/v3';
const APPLE_ROOT='https://caldav.icloud.com/';
const AGENCY_SCOPE='agency';

const sha=value=>createHash('sha256').update(String(value)).digest('hex');
function secretKey(){const value=process.env.TIE_CALENDAR_SECRET||'';assert(value.length>=32,'На сервере не настроен ключ календарей',503);return createHash('sha256').update(value).digest();}
function seal(value){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',secretKey(),iv),body=Buffer.concat([cipher.update(JSON.stringify(value)),cipher.final()]);return JSON.stringify({v:1,iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),body:body.toString('base64')});}
function open(value){try{const raw=JSON.parse(value),decipher=createDecipheriv('aes-256-gcm',secretKey(),Buffer.from(raw.iv,'base64'));decipher.setAuthTag(Buffer.from(raw.tag,'base64'));return JSON.parse(Buffer.concat([decipher.update(Buffer.from(raw.body,'base64')),decipher.final()]).toString());}catch{assert(false,'Не удалось прочитать данные подключения календаря',503);}}
function googleConfig(){const clientId=process.env.GOOGLE_CALENDAR_CLIENT_ID||'',clientSecret=process.env.GOOGLE_CALENDAR_CLIENT_SECRET||'',origin=process.env.TIE_PUBLIC_ORIGIN||'';let redirectUri='';try{const u=new URL(origin);assert(u.protocol==='https:'||['localhost','127.0.0.1'].includes(u.hostname),'Некорректный публичный адрес',503);redirectUri=new URL('/api/v2/calendar/google/callback',u).toString();}catch{redirectUri='';}return {clientId,clientSecret,redirectUri,ready:!!(clientId&&clientSecret&&redirectUri&&process.env.TIE_CALENDAR_SECRET?.length>=32)};}
function authorize(db,user,projectId,action='read'){const u=currentUser(db,user);if(projectId===AGENCY_SCOPE){assert(u.protected||can(db,u,'projects',null),'Организаторский календарь недоступен',403);const projects=entities(db,u.agency_id,null,'project').filter(project=>{try{projectAccess(db,u,project.id,action,'tasks');return !project.deleted&&!['archived'].includes(project.data.status)}catch{return false}});assert(projects.length,'Нет доступных свадеб',403);return {u,project:{id:AGENCY_SCOPE,data:{name:'Календарь организатора',timeZone:'Europe/Moscow'}},projects,aggregate:true};}const project=projectAccess(db,u,projectId,action,'tasks');return {u,project,projects:[project],aggregate:false};}
function connection(db,u,projectId,provider){return db.prepare('SELECT * FROM calendar_connections WHERE agency_id=? AND user_id=? AND project_id=? AND provider=?').get(u.agency_id,u.id,projectId,provider);}
function publicConnection(row){return row&&{provider:row.provider,displayName:row.display_name,lastSyncedAt:row.last_synced_at,lastError:row.last_error,connected:true};}
export function externalCalendarStatus(db,user,projectId){const {u}=authorize(db,user,projectId);const rows=db.prepare('SELECT * FROM calendar_connections WHERE agency_id=? AND user_id=? AND project_id=? ORDER BY provider').all(u.agency_id,u.id,projectId);return {googleConfigured:googleConfig().ready,secretConfigured:!!(process.env.TIE_CALENDAR_SECRET?.length>=32),connections:rows.map(publicConnection)};}

export function beginGoogleCalendar(db,user,projectId){const {u}=authorize(db,user,projectId,'edit'),cfg=googleConfig();assert(cfg.ready,'Google Calendar ещё не настроен на сервере',503);const state=randomBytes(32).toString('base64url'),expires=Math.floor(Date.now()/1000)+600;db.prepare('DELETE FROM calendar_oauth_states WHERE expires_at<?').run(Math.floor(Date.now()/1000));db.prepare('INSERT INTO calendar_oauth_states VALUES(?,?,?,?,?,?)').run(sha(state),u.agency_id,u.id,projectId,expires,now());const url=new URL(GOOGLE_AUTH);url.search=new URLSearchParams({client_id:cfg.clientId,redirect_uri:cfg.redirectUri,response_type:'code',scope:'https://www.googleapis.com/auth/calendar',access_type:'offline',prompt:'consent',include_granted_scopes:'true',state}).toString();return {url:url.toString()};}
async function request(url,options={},fetchImpl=fetch){let response;try{response=await fetchImpl(url,options)}catch{throw new Fault('Сервер не может связаться с календарём. Повторите позже.',502)}const text=await response.text();let value={};try{value=text?JSON.parse(text):{};}catch{value={raw:text};}if(!response.ok){const message=value?.error?.message||value?.error_description||`Календарь ответил HTTP ${response.status}`;throw new Fault(String(message).slice(0,500),response.status===410?410:response.status>=400&&response.status<500?400:502);}return {value,response};}
async function googleToken(body,fetchImpl){const cfg=googleConfig(),{value}=await request(GOOGLE_TOKEN,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...body,client_id:cfg.clientId,client_secret:cfg.clientSecret})},fetchImpl);return value;}
async function googleAccess(db,row,fetchImpl){let creds=open(row.secret_json);if(creds.accessToken&&Number(creds.expiresAt||0)>Date.now()+60000)return creds.accessToken;assert(creds.refreshToken,'Google просит подключить календарь заново',409);const token=await googleToken({grant_type:'refresh_token',refresh_token:creds.refreshToken},fetchImpl);creds={...creds,accessToken:token.access_token,expiresAt:Date.now()+Number(token.expires_in||3600)*1000};db.prepare('UPDATE calendar_connections SET secret_json=?,updated_at=? WHERE id=?').run(seal(creds),now(),row.id);return creds.accessToken;}
export async function finishGoogleCalendar(db,state,code,{fetchImpl=fetch}={}){assert(state&&code,'Google не вернул код подключения');const saved=db.prepare('SELECT * FROM calendar_oauth_states WHERE state_digest=?').get(sha(state));assert(saved&&saved.expires_at>=Math.floor(Date.now()/1000),'Ссылка подключения устарела',400);db.prepare('DELETE FROM calendar_oauth_states WHERE state_digest=?').run(sha(state));const {u,project}=authorize(db,{id:saved.user_id,agency_id:saved.agency_id},saved.project_id,'edit'),cfg=googleConfig();assert(cfg.ready,'Google Calendar ещё не настроен на сервере',503);const token=await googleToken({grant_type:'authorization_code',code,redirect_uri:cfg.redirectUri},fetchImpl);assert(token.refresh_token,'Google не выдал долгосрочный доступ. Подключите календарь заново',400);const auth={authorization:`Bearer ${token.access_token}`,'content-type':'application/json'};const {value:calendar}=await request(`${GOOGLE_API}/calendars`,{method:'POST',headers:auth,body:JSON.stringify({summary:`tie · ${project.data.name}`,timeZone:project.data.timeZone||'Europe/Moscow'})},fetchImpl);const at=now(),id=uid();transaction(db,()=>{const old=connection(db,u,project.id,'google');if(old)db.prepare('DELETE FROM calendar_connections WHERE id=?').run(old.id);db.prepare('INSERT INTO calendar_connections VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,u.agency_id,u.id,project.id,'google',calendar.summary||'Google Calendar',calendar.id,'',seal({accessToken:token.access_token,refreshToken:token.refresh_token,expiresAt:Date.now()+Number(token.expires_in||3600)*1000}),null,null,null,at,at);});return {projectId:project.id};}

const xmlDecode=value=>String(value||'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&');
const xmlEscape=value=>String(value||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function tag(block,name){return xmlDecode(block.match(new RegExp(`<[^>]*${name}[^>]*>([\\s\\S]*?)<\\/[^>]*${name}>`,'i'))?.[1]||'').trim();}
function propertyHref(xml,name){const block=String(xml).match(new RegExp(`<[^>]*${name}[^>]*>([\\s\\S]*?)<\\/[^>]*${name}>`,'i'))?.[1]||'';return tag(block,'href');}
function responses(xml){return [...String(xml).matchAll(/<[^>]*response[^>]*>([\s\S]*?)<\/[^>]*response>/gi)].map(match=>match[1]);}
const absolute=(href,base)=>new URL(xmlDecode(href),base).toString();
async function dav(url,credentials,method,body,headers={},fetchImpl=fetch){return request(url,{method,headers:{authorization:`Basic ${Buffer.from(`${credentials.appleId}:${credentials.password}`).toString('base64')}`,...body?{'content-type':'application/xml; charset=utf-8'}:{},...headers},body},fetchImpl);}
async function discoverApple(credentials,project,fetchImpl){const principalBody='<?xml version="1.0"?><d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal/></d:prop></d:propfind>',principalResult=await dav(APPLE_ROOT,credentials,'PROPFIND',principalBody,{depth:'0'},fetchImpl),principal=absolute(propertyHref(principalResult.value.raw,'current-user-principal'),principalResult.response.url||APPLE_ROOT);assert(principal,'Не найден профиль iCloud Calendar');const homeBody='<?xml version="1.0"?><d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav"><d:prop><c:calendar-home-set/></d:prop></d:propfind>',homeResult=await dav(principal,credentials,'PROPFIND',homeBody,{depth:'0'},fetchImpl),home=absolute(propertyHref(homeResult.value.raw,'calendar-home-set'),homeResult.response.url||principal);assert(home,'Не найдено хранилище календарей iCloud');const listBody='<?xml version="1.0"?><d:propfind xmlns:d="DAV:"><d:prop><d:displayname/><d:resourcetype/></d:prop></d:propfind>',listed=await dav(home,credentials,'PROPFIND',listBody,{depth:'1'},fetchImpl),wanted=`tie · ${project.data.name}`,calendars=responses(listed.value.raw).map(block=>({href:absolute(tag(block,'href'),listed.response.url||home),name:tag(block,'displayname'),calendar:/calendar\s*\/?\s*>/i.test(block)})).filter(item=>item.calendar);let selected=calendars.find(item=>item.name===wanted);if(!selected){const path=new URL(`tie-${project.id}/`,home).toString(),body=`<?xml version="1.0"?><c:mkcalendar xmlns:c="urn:ietf:params:xml:ns:caldav" xmlns:d="DAV:"><d:set><d:prop><d:displayname>${xmlEscape(wanted)}</d:displayname></d:prop></d:set></c:mkcalendar>`;await dav(path,credentials,'MKCALENDAR',body,{},fetchImpl);selected={href:path,name:wanted};}return selected;}
export async function connectAppleCalendar(db,user,{projectId,appleId,password},{fetchImpl=fetch}={}){const {u,project}=authorize(db,user,projectId,'edit');assert(/^.{3,320}$/.test(String(appleId||'')),'Укажите Apple Account');assert(/^.{8,100}$/.test(String(password||'')),'Укажите пароль приложения Apple');secretKey();const credentials={appleId:String(appleId).trim(),password:String(password).trim()},calendar=await discoverApple(credentials,project,fetchImpl),at=now(),id=uid();transaction(db,()=>{const old=connection(db,u,projectId,'apple');if(old)db.prepare('DELETE FROM calendar_connections WHERE id=?').run(old.id);db.prepare('INSERT INTO calendar_connections VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,u.agency_id,u.id,projectId,'apple',calendar.name,calendar.href,calendar.href,seal(credentials),null,null,null,at,at);});return publicConnection(connection(db,u,projectId,'apple'));}

const escapeIcs=value=>String(value||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
const unescapeIcs=value=>String(value||'').replace(/\\n/gi,'\n').replace(/\\([,;\\])/g,'$1');
const externalTitle=(task,project,aggregate)=>aggregate?`${project.data.name} — ${task.data.title}`:task.data.title;
function ics(task,project,aggregate){const stamp=now().replace(/[-:]/g,'').replace(/\.\d{3}/,'');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//tie//Wedding tasks//RU','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:tie-${task.id}@tie.event`,`DTSTAMP:${stamp}`,`DTSTART;VALUE=DATE:${task.data.dueDate.replace(/-/g,'')}`,`DTEND;VALUE=DATE:${addDays(task.data.dueDate,1).replace(/-/g,'')}`,`SUMMARY:${escapeIcs(externalTitle(task,project,aggregate))}`,`DESCRIPTION:${escapeIcs(task.data.description||'')}`,`X-TIE-TASK-ID:${task.id}`,`X-TIE-PROJECT-ID:${project.id}`,'END:VEVENT','END:VCALENDAR',''].join('\r\n');}
function parseIcs(value){const lines=String(value||'').replace(/\r\n[ \t]/g,'').split(/\r?\n/),get=name=>{const line=lines.find(item=>item.split(':',1)[0].split(';',1)[0].toUpperCase()===name);return line?unescapeIcs(line.slice(line.indexOf(':')+1)):'';},raw=get('DTSTART'),date=raw.length>=8?`${raw.slice(0,4)}-${raw.slice(4,6)}-${raw.slice(6,8)}`:'';return {uid:get('UID'),title:get('SUMMARY')||'Событие календаря',description:get('DESCRIPTION'),date,tieTaskId:get('X-TIE-TASK-ID'),tieProjectId:get('X-TIE-PROJECT-ID'),updated:get('LAST-MODIFIED')||''};}
function importedTask(db,u,project,event){return insert(db,u,'task',taskData(db,u,project,{title:event.title,description:event.description,phaseKey:'general',status:'todo',dueMode:'fixed',fixedDate:event.date,priority:'normal'}),project.id);}
function updateFromExternal(db,u,project,task,event){if(!event.date)return task;return change(db,u,task,taskData(db,u,project,{title:event.title,description:event.description,dueMode:'fixed',fixedDate:event.date},task.data),false,'calendarImport');}
function upsertLink(db,row,task,eventId,etag,updated){db.prepare(`INSERT INTO calendar_event_links(connection_id,task_id,external_event_id,external_etag,external_updated_at,last_task_version) VALUES(?,?,?,?,?,?) ON CONFLICT(connection_id,task_id) DO UPDATE SET external_event_id=excluded.external_event_id,external_etag=excluded.external_etag,external_updated_at=excluded.external_updated_at,last_task_version=excluded.last_task_version`).run(row.id,task.id,eventId,etag||null,updated||null,task.version);}
async function googleRemote(db,row,fetchImpl){const access=await googleAccess(db,row,fetchImpl),headers={authorization:`Bearer ${access}`},items=[];let pageToken='',nextSyncToken='';do{const url=new URL(`${GOOGLE_API}/calendars/${encodeURIComponent(row.calendar_ref)}/events`);url.searchParams.set('showDeleted','true');url.searchParams.set('singleEvents','true');url.searchParams.set('maxResults','2500');if(row.sync_token)url.searchParams.set('syncToken',row.sync_token);if(pageToken)url.searchParams.set('pageToken',pageToken);let result;try{result=await request(url,{headers},fetchImpl);}catch(error){if(error.status===410&&row.sync_token){db.prepare('UPDATE calendar_connections SET sync_token=NULL WHERE id=?').run(row.id);return googleRemote(db,{...row,sync_token:null},fetchImpl);}throw error;}items.push(...(result.value.items||[]));pageToken=result.value.nextPageToken||'';nextSyncToken=result.value.nextSyncToken||nextSyncToken;}while(pageToken);return {items:items.map(item=>({id:item.id,deleted:item.status==='cancelled',title:item.summary||'Событие календаря',description:item.description||'',date:item.start?.date||item.start?.dateTime?.slice(0,10)||'',tieTaskId:item.extendedProperties?.private?.tieTaskId||'',tieProjectId:item.extendedProperties?.private?.tieProjectId||'',etag:item.etag||'',updated:item.updated||''})),nextSyncToken,headers};}
async function googleWrite(row,headers,task,project,aggregate,externalId,fetchImpl){const payload={summary:externalTitle(task,project,aggregate),description:task.data.description||'',start:{date:task.data.dueDate},end:{date:addDays(task.data.dueDate,1)},extendedProperties:{private:{tieTaskId:task.id,tieProjectId:project.id}}},url=externalId?`${GOOGLE_API}/calendars/${encodeURIComponent(row.calendar_ref)}/events/${encodeURIComponent(externalId)}`:`${GOOGLE_API}/calendars/${encodeURIComponent(row.calendar_ref)}/events`,result=await request(url,{method:externalId?'PUT':'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify(payload)},fetchImpl);return {id:result.value.id,etag:result.value.etag,updated:result.value.updated};}
async function appleRemote(row,fetchImpl){const credentials=open(row.secret_json),body='<?xml version="1.0"?><c:calendar-query xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav"><d:prop><d:getetag/><c:calendar-data/></d:prop><c:filter><c:comp-filter name="VCALENDAR"><c:comp-filter name="VEVENT"/></c:comp-filter></c:filter></c:calendar-query>',result=await dav(row.calendar_ref,credentials,'REPORT',body,{depth:'1'},fetchImpl),items=responses(result.value.raw).map(block=>{const event=parseIcs(tag(block,'calendar-data'));return {...event,id:absolute(tag(block,'href'),row.calendar_ref),etag:tag(block,'getetag'),deleted:false};}).filter(item=>item.date);return {items,credentials};}
async function appleWrite(row,credentials,task,project,aggregate,externalId,fetchImpl){const id=externalId||new URL(`tie-${task.id}.ics`,row.calendar_ref).toString(),result=await dav(id,credentials,'PUT',ics(task,project,aggregate),{'content-type':'text/calendar; charset=utf-8',...(externalId?{}:{'if-none-match':'*'})},fetchImpl);return {id,etag:result.response.headers.get('etag')||'',updated:now()};}
export async function syncExternalCalendar(db,user,{projectId,provider},{fetchImpl=fetch}={}){
 const {u,projects,aggregate}=authorize(db,user,projectId,'edit'),row=connection(db,u,projectId,provider);assert(row,'Календарь не подключён',404);for(const project of projects)requireAccess(db,u,'edit',project.id,'tasks',null,null);
 const byProject=new Map(projects.map(project=>[project.id,project]));
 try{
  const remote=provider==='google'?await googleRemote(db,row,fetchImpl):await appleRemote(row,fetchImpl),links=()=>db.prepare('SELECT * FROM calendar_event_links WHERE connection_id=?').all(row.id),byExternal=new Map(links().map(link=>[link.external_event_id,link]));let imported=0,updated=0,exported=0,ignored=0;
  for(const rawEvent of remote.items){let link=byExternal.get(rawEvent.id),task=link?entity(db,link.task_id):(rawEvent.tieTaskId?entity(db,rawEvent.tieTaskId):null),project=(task?byProject.get(task.project_id):byProject.get(rawEvent.tieProjectId))||(!aggregate?projects[0]:null);
   if(!project&&aggregate)project=[...projects].sort((a,b)=>b.data.name.length-a.data.name.length).find(item=>rawEvent.title.startsWith(`${item.data.name} — `));
   if(rawEvent.deleted){if(link&&task&&!task.deleted&&task.version===link.last_task_version){change(db,u,task,task.data,true,'calendarDelete');updated++;}continue;}
   if(!project){ignored++;continue;}
   const prefix=`${project.data.name} — `,event={...rawEvent,title:aggregate&&rawEvent.title.startsWith(prefix)?rawEvent.title.slice(prefix.length):rawEvent.title};
   if(!task||task.project_id!==project.id||task.kind!=='task'){task=importedTask(db,u,project,event);imported++;}
   else if(link&&task.version===link.last_task_version&&((event.updated||'')>(link.external_updated_at||'')||provider==='apple'&&event.etag&&event.etag!==link.external_etag)){task=updateFromExternal(db,u,project,task,event);updated++;}
   upsertLink(db,row,task,event.id,event.etag,event.updated);
  }
  if(provider==='apple'){const present=new Set(remote.items.map(event=>event.id));for(const link of links())if(!present.has(link.external_event_id)){const task=entity(db,link.task_id);if(task&&!task.deleted&&task.version===link.last_task_version&&byProject.has(task.project_id)){change(db,u,task,task.data,true,'calendarDelete');updated++;}db.prepare('DELETE FROM calendar_event_links WHERE connection_id=? AND task_id=?').run(row.id,link.task_id);}}
  const allTasks=projects.flatMap(project=>entities(db,u.agency_id,project.id,'task',true)),linkMap=new Map(links().map(link=>[link.task_id,link]));
  for(const task of allTasks){const project=byProject.get(task.project_id);let link=linkMap.get(task.id);if(task.deleted||['done','skipped'].includes(task.data.status)||!task.data.dueDate){if(link){if(provider==='google')await request(`${GOOGLE_API}/calendars/${encodeURIComponent(row.calendar_ref)}/events/${encodeURIComponent(link.external_event_id)}`,{method:'DELETE',headers:remote.headers},fetchImpl);else await dav(link.external_event_id,remote.credentials,'DELETE',null,{},fetchImpl);db.prepare('DELETE FROM calendar_event_links WHERE connection_id=? AND task_id=?').run(row.id,task.id);}continue;}if(!link||task.version>link.last_task_version){const saved=provider==='google'?await googleWrite(row,remote.headers,task,project,aggregate,link?.external_event_id,fetchImpl):await appleWrite(row,remote.credentials,task,project,aggregate,link?.external_event_id,fetchImpl);upsertLink(db,row,task,saved.id,saved.etag,saved.updated);exported++;}}
  const at=now();db.prepare('UPDATE calendar_connections SET sync_token=?,last_synced_at=?,last_error=NULL,updated_at=? WHERE id=?').run(provider==='google'?remote.nextSyncToken||row.sync_token:null,at,at,row.id);return {provider,imported,updated,exported,ignored,lastSyncedAt:at};
 }catch(error){db.prepare('UPDATE calendar_connections SET last_error=?,updated_at=? WHERE id=?').run(String(error.message||error).slice(0,500),now(),row.id);throw error;}
}
let backgroundSync=false;
export async function syncDueExternalCalendars(db,{max=10,fetchImpl=fetch}={}){if(backgroundSync)return {skipped:true};backgroundSync=true;let synced=0;try{const cutoff=new Date(Date.now()-5*60000).toISOString(),rows=db.prepare('SELECT * FROM calendar_connections WHERE last_synced_at IS NULL OR last_synced_at<? ORDER BY coalesce(last_synced_at,created_at) LIMIT ?').all(cutoff,max);for(const row of rows){try{await syncExternalCalendar(db,{id:row.user_id,agency_id:row.agency_id},{projectId:row.project_id,provider:row.provider},{fetchImpl});synced++;}catch{/* Safe error text is stored on the connection for its owner. */}}return {synced};}finally{backgroundSync=false;}}
export function disconnectExternalCalendar(db,user,{projectId,provider}){const {u}=authorize(db,user,projectId,'edit'),row=connection(db,u,projectId,provider);assert(row,'Календарь не подключён',404);db.prepare('DELETE FROM calendar_connections WHERE id=?').run(row.id);return {ok:true};}
