import { assert, entities, entity, change, version, now } from '../../db.mjs';
import { can, requireAccess } from '../../auth.mjs';
import { financials, projectVisible, text } from '../../model.mjs';
import { currentUser, projectAccess, scoped, localDate, addDays, zonedInstant, validateMembers, timeZone } from '../common.mjs';
import { calendar, conflicts } from './index.mjs';
const link=(p,path,id='')=>`/app/projects/${p}/${path}${id?'/'+id:''}`;
const known=(db,u,p,section,action='read')=>can(db,u,action,p,section,null,null);
function policy(rule){if(typeof rule==='boolean')return {required:rule,reason:rule?'':'Отключено в настройках'};return rule||{};}
function allowedRecord(db,u,r,section,fields){return can(db,u,'read',r.project_id,section,r.id,fields);}
function guestFields(m){return {name:m.guestName||m.name,rsvp:m.rsvpStatus||m.rsvp,values:m.rsvpValues||{},table:m.seatingTable,seat:m.seatIndex};}
function rsvpValue(row,m){const value=row.data[m.rsvp];return Object.entries(m.values).find(([,v])=>v===value)?.[0]||(['confirmed','declined','tentative'].includes(value)?value:'unanswered');}
const tableExists=(db,name)=>!!db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(name);
export function readiness(db,user,projectId,at=Date.now()) {
 const u=currentUser(db,user),p=projectAccess(db,u,projectId),all=entities(db,u.agency_id,projectId),today=localDate(at,p.data.timeZone||'Europe/Moscow'),checkedAt=new Date(at).toISOString(),checks=[],attention=[];
 const activeSnooze=(key,sourceId='')=>db.prepare('SELECT until_at FROM readiness_snoozes WHERE user_id=? AND project_id=? AND rule_key=? AND source_id IN (?,\'\') AND until_at>? ORDER BY source_id DESC LIMIT 1').get(u.id,projectId,key,sourceId,checkedAt);
 const add=(key,state,summary,reason,path,sourceRefs=[])=>{const snooze=activeSnooze(key);const r={ruleKey:key,state,summary,reason,sourceRefs,actionUrl:link(projectId,path),snoozedUntil:snooze?.until_at||null,checkedAt};checks.push(r);return r;};
 const warn=(key,r,title,due,path,priority=0)=>{if(activeSnooze(key,r.id))return;attention.push({id:key+':'+r.id,ruleKey:key,sourceKind:r.kind,sourceId:r.id,sourceVersion:r.version,projectId,projectName:p.data.name,title,dueDate:due||'',assigneeUserId:r.data.assigneeUserId||r.data.responsible||null,priority,actionUrl:link(projectId,path,r.id)});};
 const applyPolicy=(key,summary,path)=>{const settings=policy(p.data.readinessPolicy?.[key]);if(settings.required===false){add(key,'not_applicable',summary,settings.reason||'Отключено в настройках проекта',path);return false;}if(settings.required!==true){add(key,'unknown',summary,'Не настроена обязательность проверки',path);return false;}return true;};
 if(applyPolicy('contract','Договор отмечен','files')){
  if(!known(db,u,projectId,'files',['read','files']))add('contract','unknown','Договор отмечен','Недостаточно доступа к файлам','files');
  else{const docs=all.filter(r=>r.kind==='file'&&r.data.documentKind==='contract');const confirmed=docs.filter(r=>r.data.verificationStatus==='confirmed'&&r.data.verifiedBy&&r.data.verifiedAt);add('contract',confirmed.length?'pass':'warning','Договор отмечен',confirmed.length?'Проверка подтверждена участником проекта':'Добавьте договор и отметьте его проверку','files',docs.map(r=>({kind:r.kind,id:r.id})));}
 }
 if(applyPolicy('booking','Бронь подрядчиков подтверждена','vendors')){
  if(!known(db,u,projectId,'vendors'))add('booking','unknown','Бронь подрядчиков подтверждена','Недостаточно доступа к услугам','vendors');
  else{const selected=all.filter(r=>r.kind==='selection'&&r.data.selected),required=selected.filter(r=>r.data.bookingRequired===true),missing=required.filter(r=>r.data.bookingStatus!=='confirmed'||!r.data.bookingVerifiedBy||!r.data.bookingVerifiedAt||!r.data.bookingEvidenceFileId&&!r.data.bookingEvidenceNote),undefinedPolicy=selected.filter(r=>r.data.bookingRequired==null);const state=missing.length?'warning':!selected.length||undefinedPolicy.length?'unknown':'pass';add('booking',state,'Бронь подрядчиков подтверждена',missing.length?`Нужна проверка ${missing.length} услуг`:undefinedPolicy.length?'У части услуг не указана обязательность брони':!selected.length?'Выбранные услуги пока не заполнены':'Все необходимые брони подтверждены','vendors',missing.map(r=>({kind:r.kind,id:r.id})));}
 }
 const tasks=all.filter(r=>r.kind==='task'&&allowedRecord(db,u,r,'tasks',['title','status','dueDate','assigneeUserId'])),activeTasks=tasks.filter(r=>r.data.status!=='skipped'),done=activeTasks.filter(r=>r.data.status==='done'),overdue=activeTasks.filter(r=>r.data.status!=='done'&&r.data.dueDate&&r.data.dueDate<today);
 for(const r of overdue)warn('tasks',r,r.data.title,r.data.dueDate,'tasks');
 if(!known(db,u,projectId,'tasks'))add('tasks','unknown','Просроченных задач нет','Недостаточно доступа ко всему плану','tasks');else if(!tasks.length)add('tasks','unknown','Просроченных задач нет','План не заполнен','tasks');else add('tasks',overdue.length?'warning':'pass','Просроченных задач нет',overdue.length?`Просрочено задач: ${overdue.length}`:'Сроки активных задач проверены','tasks',overdue.map(r=>({kind:r.kind,id:r.id})));
 const financialAccess=known(db,u,projectId,'budget',['read','finance']);let finance=null;
 if(financialAccess){const f=financials(all),moves=all.filter(r=>r.kind==='movement'),received=moves.filter(r=>r.data.type==='deposit').reduce((s,r)=>s+r.data.amount,0),returned=moves.filter(r=>r.data.type==='refund').reduce((s,r)=>s+r.data.amount,0);finance={...f,received,returned};add('receipts','unknown','Поступления от пары учтены','Отражены фактические поступления и возвраты. План предоплаты не задан.','finance/estimate');checks.at(-1).amounts={received,returned,net:received-returned};
  const obligations=all.filter(r=>r.kind==='obligation'),debts=obligations.filter(r=>r.data.agreed!==null&&r.data.agreed-(f.paid[r.id]||0)>0),late=debts.filter(r=>r.data.dueDate&&r.data.dueDate<today),unknown=obligations.filter(r=>r.data.priceKind==='unknown'||r.data.agreed-(f.paid[r.id]||0)>0&&!r.data.dueDate);add('payments',late.length?'warning':unknown.length?'unknown':obligations.length?'pass':'unknown','Просроченных выплат нет',late.length?`Просрочено выплат: ${late.length}`:unknown.length?`Не определены цена или срок: ${unknown.length}`:obligations.length?'Все известные сроки проверены':'Смета не заполнена','finance/payouts',[...late,...unknown].map(r=>({kind:r.kind,id:r.id})));
  for(const r of debts)if(r.data.dueDate&&r.data.dueDate<=addDays(today,7))warn('payments',r,r.data.title,r.data.dueDate,'finance/estimate',r.data.dueDate<today?0:r.data.dueDate===today?1:2);
 }else{add('receipts','unknown','Поступления от пары учтены','Недостаточно доступа к финансовому журналу','finance/estimate');add('payments','unknown','Просроченных выплат нет','Недостаточно доступа к финансовому журналу','finance/payouts');}
 for(const a of all.filter(r=>r.kind==='approval'&&allowedRecord(db,u,r,'approvals',['title','state','dueDate','currentRevisionId']))){
  if(['approved','draft','withdrawn'].includes(a.data.state))continue;const revision=entity(db,a.data.currentRevisionId);let voted=false;if(revision&&tableExists(db,'approval_votes'))voted=!!db.prepare('SELECT 1 FROM approval_votes WHERE revision_id=? AND user_id=?').get(revision.id,u.id);
  const needsMe=revision?.data.approverUserIds?.includes(u.id)&&!voted,late=a.data.dueDate&&a.data.dueDate<today;if(needsMe||late)warn('approvals',a,a.data.title,a.data.dueDate,'approvals',late?0:1);
 }
 const guestTable=all.find(r=>r.kind==='table'&&r.data.key==='guests'),map=guestTable?.data.semanticMap?guestFields(guestTable.data.semanticMap):null,guestAllowed=guestTable&&known(db,u,projectId,guestTable.id),guests=guestTable?all.filter(r=>r.kind==='row'&&r.parent_id===guestTable.id):[],microsite=all.find(r=>r.kind==='microsite');let confirmed=[];
 if(!map?.rsvp||!guestAllowed||!known(db,u,projectId,'microsite'))add('rsvp','unknown','Гости ответили','Нужно сопоставить поля гостей и предоставить доступ к сроку RSVP','guests');
 else{const deadline=microsite?.data.rsvpDeadline,invites=tableExists(db,'guest_invites')?db.prepare('SELECT * FROM guest_invites WHERE project_id=?').all(projectId).filter(r=>!r.revoked_at&&r.expires_at>at):[],invitedIds=new Set(tableExists(db,'guest_invite_rows')?invites.flatMap(i=>db.prepare('SELECT guest_row_id FROM guest_invite_rows WHERE invite_id=?').all(i.id).map(r=>r.guest_row_id)):[]),unanswered=guests.filter(r=>invitedIds.has(r.id)&&rsvpValue(r,map)==='unanswered'),tentative=guests.filter(r=>invitedIds.has(r.id)&&rsvpValue(r,map)==='tentative');confirmed=guests.filter(r=>rsvpValue(r,map)==='confirmed');
  const late=deadline&&deadline<today;add('rsvp',!deadline||!invites.length?'unknown':unanswered.length||tentative.length?late?'warning':'unknown':'pass','Гости ответили',!deadline?'Срок ответа не задан':!invites.length?'Активные приглашения не созданы':`Без ответа: ${unanswered.length}; пока не решили: ${tentative.length}${!late?' — ожидаем до срока':''}`,'guests',[...unanswered,...tentative].map(r=>({kind:r.kind,id:r.id})));
  if(late)for(const r of unanswered)warn('rsvp',r,r.data[map.name]||'Ответ гостя',deadline,'guests');
 }
 if(applyPolicy('seating','Подтвердившие гости рассажены','seating')){
  const plan=all.find(r=>r.kind==='seatingPlan'),tables=all.filter(r=>r.kind==='seatingTable');if(!plan||!map?.table||!map?.seat||!guestAllowed||!known(db,u,projectId,'seating'))add('seating','unknown','Подтвердившие гости рассажены','Нужны план зала, сопоставление полей и доступ к гостям','seating');
  else{confirmed=guests.filter(r=>rsvpValue(r,map)==='confirmed');const seats=new Map();for(const r of guests){const key=r.data[map.table]+':'+r.data[map.seat];if(r.data[map.table])seats.set(key,(seats.get(key)||0)+1);}const missing=confirmed.filter(r=>{const t=tables.find(t=>t.id===r.data[map.table]),index=r.data[map.seat];return !t||!Number.isInteger(index)||index<1||index>t.data.capacity||seats.get(t.id+':'+index)>1;});add('seating',missing.length?'warning':'pass','Подтвердившие гости рассажены',missing.length?`Нужны места: ${missing.length}`:`Проверено мест: ${confirmed.length}`,'seating',missing.map(r=>({kind:r.kind,id:r.id})));for(const r of missing)warn('seating',r,r.data[map.name]||'Гость без места','', 'seating');}
 }
 if(applyPolicy('timing','Программа дня заполнена','day/team')){
  const t=all.find(r=>r.kind==='table'&&r.data.key==='timing'),m=t?.data.semanticMap;if(!t||!m?.startTime||!m?.title||!m?.required||!known(db,u,projectId,t.id))add('timing','unknown','Программа дня заполнена','Нужно сопоставить название, время и обязательность пунктов','day/team');
  else{const rows=all.filter(r=>r.kind==='row'&&r.parent_id===t.id),required=rows.filter(r=>r.data[m.required]===true),invalid=required.filter(r=>{try{if(!r.data[m.title])return true;const day=addDays(p.data.date,Number(r.data[m.dayOffset]||0)),start=zonedInstant(day,r.data[m.startTime],p.data.timeZone);if(m.endTime&&r.data[m.endTime]){const end=zonedInstant(addDays(day,Number(r.data[m.endDayOffset]||0)),r.data[m.endTime],p.data.timeZone);if(end<start)return true;}return false;}catch{return true;}});add('timing',!rows.length||!required.length?'unknown':invalid.length?'warning':'pass','Программа дня заполнена',!rows.length?'Программа не заполнена':!required.length?'Обязательные пункты не отмечены':invalid.length?`Проверьте время и названия: ${invalid.length}`:'Обязательные пункты проверены','day/team',invalid.map(r=>({kind:r.kind,id:r.id})));}
 }
 for(const m of all.filter(r=>r.kind==='meeting'&&allowedRecord(db,u,r,'calendar',['title','startAt','endAt','assignedUserIds','participantUserIds'])))if(conflicts(db,u,m.data,m.id).length)warn('calendar',m,m.data.title,localDate(m.data.startAt,p.data.timeZone),'calendar');
 attention.sort((a,b)=>a.priority-b.priority||a.dueDate.localeCompare(b.dueDate)||a.id.localeCompare(b.id));
 return {projectId,checkedAt,today,checks,attention,progress:{done:done.length,total:activeTasks.length,ratio:activeTasks.length?done.length/activeTasks.length:null},financials:finance,guestCount:guestAllowed?guests.length:null,confirmedCount:guestAllowed&&map?confirmed.length:null,daysToWedding:p.data.date?Math.round((Date.parse(p.data.date)-Date.parse(today))/86400000):null};
}
export function dashboard(db,user,q={}){
 const u=currentUser(db,user),at=q.at||Date.now(),day=localDate(at),projects=entities(db,u.agency_id,null,'project').filter(p=>!['completed','archived'].includes(p.data.status)&&projectVisible(db,u,p.id)&&(!q.projectId||q.projectId===p.id));if(q.projectId)projectAccess(db,u,q.projectId);
 const reports=projects.map(p=>readiness(db,u,p.id,at)),attention=reports.flatMap(r=>r.attention).filter(a=>(!q.assignee||a.assigneeUserId===q.assignee)&&(!q.type||a.ruleKey===q.type)).sort((a,b)=>a.priority-b.priority||a.dueDate.localeCompare(b.dueDate)||a.id.localeCompare(b.id));
 const applications=can(db,u,'applications')?entities(db,u.agency_id,null,'application').filter(a=>['review','clarification'].includes(a.data.status)).length:null,nearest=projects.filter(p=>p.data.date>=day).sort((a,b)=>a.data.date.localeCompare(b.data.date))[0];
 return {metrics:{activeProjects:projects.length,pendingApplications:applications,overdueTasks:reports.reduce((sum,r)=>sum+r.attention.filter(a=>a.ruleKey==='tasks').length,0),nearestWedding:nearest?{id:nearest.id,name:nearest.data.name,date:nearest.data.date}:null},attention:q.all?attention:attention.slice(0,8),attentionTotal:attention.length,upcoming:calendar(db,u,{from:day,to:addDays(day,6),projectId:q.projectId,assignee:q.assignee}).items,...(q.projectId?{readiness:reports[0]}:{})};
}
const verifyAuth=(db,u,c)=>{const kind=c.op==='file.verify'?'file':'selection',section=kind==='file'?'files':'vendors',r=scoped(db,u,c.entityId,c.projectId,kind);requireAccess(db,u,kind==='file'?['edit','files']:'edit',c.projectId,section,r.id,kind==='file'?['documentKind','verificationStatus','verifiedBy','verifiedAt','verificationNote']:['bookingRequired','bookingStatus','bookingVerifiedBy','bookingVerifiedAt','bookingEvidenceFileId','bookingEvidenceNote']);};
export const readinessOperations={
 'project.readinessSettings':{authorize(db,u,c){projectAccess(db,u,c.projectId,'edit','project',c.projectId,Object.keys(c.data||{}));},run(db,u,c){const p=entity(db,c.projectId);version(p,c.version);const d=c.data||{},next={...p.data};if(d.timeZone){timeZone(d.timeZone);assert(d.timeZone===(p.data.timeZone||'Europe/Moscow'),'Для смены часового пояса используйте предпросмотр переноса даты',409);}if(d.readinessPolicy){for(const [key,value]of Object.entries(d.readinessPolicy)){assert(['contract','booking','timing','seating'].includes(key),'Неизвестная проверка');assert(typeof value.required==='boolean','Укажите обязательность');if(!value.required)text(value.reason,'Причина отключения',3,1000);}next.readinessPolicy=d.readinessPolicy;}if(Object.hasOwn(d,'leadOrganizerUserId')){if(d.leadOrganizerUserId)validateMembers(db,u,c.projectId,[d.leadOrganizerUserId]);next.leadOrganizerUserId=d.leadOrganizerUserId||null;}if(d.staffIntervals){assert(Array.isArray(d.staffIntervals)&&d.staffIntervals.length<=100,'Проверьте интервалы');validateMembers(db,u,c.projectId,[...new Set(d.staffIntervals.map(i=>i.userId))]);next.staffIntervals=d.staffIntervals.map(i=>{const startAt=i.startLocal?zonedInstant(i.startLocal.slice(0,10),i.startLocal.slice(11,16),p.data.timeZone||'Europe/Moscow',i.ambiguity):i.startAt,endAt=i.endLocal?zonedInstant(i.endLocal.slice(0,10),i.endLocal.slice(11,16),p.data.timeZone||'Europe/Moscow',i.ambiguity):i.endAt;assert(Number.isFinite(Date.parse(startAt))&&Number.isFinite(Date.parse(endAt))&&Date.parse(startAt)<Date.parse(endAt),'Проверьте интервал работы');return {userId:i.userId,startAt:new Date(startAt).toISOString(),endAt:new Date(endAt).toISOString()};});}return change(db,u,p,next);}},
 'file.verify':{authorize:verifyAuth,run(db,u,c){const r=entity(db,c.entityId);version(r,c.version);assert(['contract','other'].includes(c.documentKind)&&['confirmed','unverified'].includes(c.status),'Проверьте вид и статус файла');return change(db,u,r,{...r.data,documentKind:c.documentKind,verificationStatus:c.status,verifiedBy:c.status==='confirmed'?u.id:null,verifiedAt:c.status==='confirmed'?now():null,verificationNote:c.note?text(c.note,'Комментарий',1,2000):''},false,'verify');}},
 'selection.booking':{authorize:verifyAuth,run(db,u,c){const r=entity(db,c.entityId);version(r,c.version);assert(typeof c.required==='boolean'&&['unknown','requested','confirmed','cancelled'].includes(c.status),'Проверьте бронь');if(c.fileId){const file=scoped(db,u,c.fileId,c.projectId,'file');requireAccess(db,u,['read','files'],c.projectId,'files',file.id);}if(c.status==='confirmed')assert(c.fileId||c.note?.trim(),'Укажите основание подтверждения брони');return change(db,u,r,{...r.data,bookingRequired:c.required,bookingStatus:c.status,bookingVerifiedBy:c.status==='confirmed'?u.id:null,bookingVerifiedAt:c.status==='confirmed'?now():null,bookingEvidenceFileId:c.fileId||null,bookingEvidenceNote:c.note?text(c.note,'Основание',1,2000):''},false,'booking');}},
};
