import React, { useMemo, useState } from 'react';
import './guest.css';

const labels={guestName:'Имя гостя',rsvpStatus:'Ответ RSVP',diet:'Питание',allergies:'Ограничения',transfer:'Трансфер',accommodation:'Проживание',contact:'Контакт',comment:'Комментарий',invitationStatus:'Статус ссылки',seatingTable:'Стол',seatIndex:'Место'};
const rsvpLabel={unanswered:'Нет ответа',confirmed:'Приду',declined:'Не смогу',tentative:'Пока не знаю'};
const uid=()=>globalThis.crypto?.randomUUID?.()||`guest_${Date.now()}_${Math.random().toString(36).slice(2)}`;

function guestTable(state) { return (state?.entities||[]).find(item=>item.kind==='table'&&item.data?.key==='guests'); }
function rows(state, table) { return (state?.entities||[]).filter(item=>item.kind==='row'&&item.parent_id===table?.id&&!item.deleted); }

export function GuestMappingWizard({state,projectId,run,refresh}) {
  const table=guestTable(state); const [draft,setDraft]=useState(()=>table?.data?.semanticMap||{}); const [error,setError]=useState('');
  if(!table) return <p className="v2-guest-empty">В проекте пока нет реестра гостей.</p>;
  const columns=table.data.columns||[];
  const save=async()=>{setError('');try{await run('guestMapping.save',{projectId,guestTableId:table.id,schemaVersion:table.version,data:{semanticMap:draft},confirm:true});await refresh();}catch(e){setError(e.message||'Не удалось сохранить сопоставление');}};
  return <section className="v2-guest-card"><h2>Поля RSVP</h2><p>Связываем функции с ID колонок. Переименование заголовка не изменит ответ гостя.</p><div className="v2-guest-mapping">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<select value={draft[key]||''} onChange={e=>setDraft({...draft,[key]:e.target.value||undefined})}><option value="">Не использовать</option>{columns.map(column=><option key={column.id} value={column.id}>{column.name} · {column.type}</option>)}</select></label>)}</div>{error&&<p role="alert" className="v2-guest-error">{error}</p>}<button onClick={save}>Сохранить сопоставление</button></section>;
}

export function GuestWorkspace({state,projectId,run,refresh,navigate}) {
  const table=guestTable(state); const allRows=rows(state,table); const map=table?.data?.semanticMap||{}; const [filter,setFilter]=useState('all'); const [selected,setSelected]=useState(new Set()); const [link,setLink]=useState(''); const [expiry,setExpiry]=useState('');
  const status=row=>{const raw=row.data?.[map.rsvpStatus]; for(const [key,value] of Object.entries(map.rsvpValues||{}))if(value===raw)return key; return ['confirmed','declined','tentative'].includes(raw)?raw:'unanswered';};
  const filtered=allRows.filter(row=>filter==='all'||status(row)===filter); const toggle=id=>setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next;});
  const invite=async()=>{if(!selected.size)return;const result=await run('guestInvite.create',{projectId,guestTableId:table.id,schemaVersion:table.version,guestRowIds:[...selected],expiresAt:expiry?new Date(expiry).toISOString():new Date(Date.now()+30*864e5).toISOString()});setLink(result.token?`${location.origin}/w/${state.microsite?.shareId||':shareId'}#invite=${result.token}`:'');await refresh();};
  if(!table) return <GuestMappingWizard {...{state,projectId,run,refresh}}/>;
  return <section className="v2-guest-workspace"><header><div><h1>Гости</h1><p>{allRows.filter(row=>status(row)==='confirmed').length} подтвердили · {allRows.filter(row=>status(row)==='unanswered').length} без ответа</p></div><button onClick={()=>navigate?.(`/app/projects/${projectId}/seating`)}>Открыть рассадку</button></header><div className="v2-guest-toolbar"><label>Фильтр <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Все</option>{Object.entries(rsvpLabel).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Срок ссылки <input type="datetime-local" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><button disabled={!selected.size} onClick={invite}>Создать приглашение ({selected.size})</button></div>{link&&<p className="v2-guest-link"><strong>Скопируйте ссылку сейчас:</strong> <code>{link}</code></p>}<div className="v2-guest-table-wrap"><table><thead><tr><th scope="col">Выбор</th><th scope="col">Гость</th><th scope="col">Ответ</th><th scope="col">Питание</th><th scope="col">Стол</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><input aria-label={`Выбрать ${row.data[map.guestName]||'гостя'}`} type="checkbox" checked={selected.has(row.id)} onChange={()=>toggle(row.id)}/></td><th scope="row">{row.data[map.guestName]||'Без имени'}</th><td><span className={`v2-guest-status is-${status(row)}`}>{rsvpLabel[status(row)]}</span></td><td>{row.data[map.diet]||'—'}</td><td>{row.data[map.seatingTable]||'—'}</td></tr>)}</tbody></table></div></section>;
}

export function SeatingWorkspace({state,projectId,run,refresh}) {
  const plans=(state?.entities||[]).filter(item=>item.kind==='seatingPlan'&&!item.deleted); const plan=plans[0]; const tables=(state?.entities||[]).filter(item=>item.kind==='seatingTable'&&item.parent_id===plan?.id&&!item.deleted); const guests=rows(state,guestTable(state)); const map=guestTable(state)?.data?.semanticMap||{}; const [selected,setSelected]=useState(null); const [newTable,setNewTable]=useState({label:'Стол',shape:'round',capacity:8,xM:1,yM:1,widthM:1.6,heightM:1.6}); const [seat,setSeat]=useState(1); const add=async()=>{if(plan) await run('seatingTable.create',{projectId,planId:plan.id,planVersion:plan.version,data:newTable}); else await run('seatingPlan.save',{projectId,data:{name:'План зала',widthM:12,heightM:8,scale:1,guestTableId:guestTable(state)?.id}});await refresh();}; const unseated=guests.filter(row=>!row.data[map.seatingTable]&&row.data[map.rsvpStatus]!=='declined'); const assign=async guest=>{if(!selected)return;await run('seating.assign',{projectId,guestTableId:guestTable(state).id,guestRowId:guest.id,rowVersion:guest.version,tableId:selected.id,seatIndex:seat});await refresh();};
  return <section className="v2-seat"><header><h1>Рассадка</h1><button onClick={()=>window.print()}>Печать A4/A3</button></header><div className="v2-seat-toolbar"><input value={newTable.label} onChange={e=>setNewTable({...newTable,label:e.target.value})} aria-label="Название стола"/><label>Мест <input type="number" min="1" max="30" value={newTable.capacity} onChange={e=>setNewTable({...newTable,capacity:+e.target.value})}/></label><button onClick={add}>{plan?'Добавить стол':'Создать план'}</button></div>{plan&&<div className="v2-seat-layout"><div className="v2-seat-canvas" style={{aspectRatio:`${plan.data.widthM}/${plan.data.heightM}`}} aria-label="План зала">{tables.map(item=><button key={item.id} className={`v2-seat-table is-${item.data.shape} ${selected?.id===item.id?'is-selected':''}`} style={{left:`${item.data.xM/plan.data.widthM*100}%`,top:`${item.data.yM/plan.data.heightM*100}%`,width:`${item.data.widthM/plan.data.widthM*100}%`,height:`${item.data.heightM/plan.data.heightM*100}%`,transform:`rotate(${item.data.rotationDeg}deg)`}} onClick={()=>setSelected(item)}>{item.data.label}<small>{item.data.capacity} мест</small></button>)}</div><aside><h2>Нерассаженные</h2>{unseated.map(guest=><div className="v2-seat-guest" key={guest.id}><span>{guest.data[map.guestName]||'Без имени'}</span><label>Место <input type="number" min="1" max={selected?.data.capacity||1} value={seat} onChange={e=>setSeat(+e.target.value)}/></label><button disabled={!selected} onClick={()=>assign(guest)}>Посадить</button></div>)}<p className="v2-seat-note">Выберите стол, затем гостя и место. Этот путь доступен с клавиатуры и на телефоне.</p></aside></div>}</section>;
}

export function PublicRsvp({context,submit}) { const [draft,setDraft]=useState(()=>Object.fromEntries((context.guests||[]).map(guest=>[guest.id,{name:guest.name,rsvp:guest.rsvp||'unanswered',diet:guest.diet||'',allergies:guest.allergies||'',comment:guest.comment||''}]))); const [message,setMessage]=useState(''); const send=async()=>{try{await submit(Object.entries(draft).map(([rowId,values])=>({rowId,rowVersion:context.guests.find(g=>g.id===rowId).version,values})));setMessage('Ответ сохранён');}catch(error){setMessage(error.message||'Не удалось сохранить ответ');}};return <main className="v2-rsvp"><h1>Ваш ответ на приглашение</h1>{(context.guests||[]).map(guest=><fieldset key={guest.id}><legend>{guest.name||'Гость'}</legend><label>Имя <input value={draft[guest.id].name} disabled={!context.canRespond&&!guest.isPlusOne} onChange={e=>setDraft({...draft,[guest.id]:{...draft[guest.id],name:e.target.value}})}/></label><label>Присутствие <select value={draft[guest.id].rsvp} disabled={!context.canRespond} onChange={e=>setDraft({...draft,[guest.id]:{...draft[guest.id],rsvp:e.target.value}})}>{Object.entries(rsvpLabel).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Питание <input value={draft[guest.id].diet} disabled={!context.canRespond} onChange={e=>setDraft({...draft,[guest.id]:{...draft[guest.id],diet:e.target.value}})}/></label><label>Ограничения <textarea value={draft[guest.id].allergies} disabled={!context.canRespond} onChange={e=>setDraft({...draft,[guest.id]:{...draft[guest.id],allergies:e.target.value}})}/></label></fieldset>)}{context.canRespond?<button onClick={send}>Отправить ответ</button>:<p>Срок ответов завершён. Ниже показан ваш сохранённый ответ.</p>}{message&&<p role="status">{message}</p>}</main>;
}
